
const infoproductores = [
    {
        codigo: "M7001",
        huerto: 01,
        sector: 02,
        especie: "arandano",
        variedad: "biloxy",
    },
    {
        codigo: "M7002",
        huerto: 02,
        sector: 03,
        especie: "zarzamora",
        variedad: "tupi",
    },
    {
        codigo: "M7003",
        huerto: 03,
        sector: 05,
        especie: "frambuesa",
        variedad: "purple",
    },
    {
        codigo: "M7004",
        huerto: 11,
        sector: 32,
        especie: "arandano",
        variedad: "biloxy",
    },
    {
        codigo: "M7005",
        huerto: 12,
        sector: 03,
        especie: "zarzamora",
        variedad: "tupi",
    },
    {
        codigo: "M7006",
        huerto: 03,
        sector: 25,
        especie: "frambuesa",
        variedad: "purple",
    },
    {
        codigo: "M7007",
        huerto: 15,
        sector: 06,
        especie: "arandano",
        variedad: "biloxy",
    },
    {
        codigo: "M7008",
        huerto: 12,
        sector: 33,
        especie: "zarzamora",
        variedad: "tupi",
    },
    {
        codigo: "M7009",
        huerto: 30,
        sector: 20,
        especie: "frambuesa",
        variedad: "purple",
    },
    {
        codigo: "M7010",
        huerto: 11,
        sector: 23,
        especie: "arandano",
        variedad: "biloxy",
    },
    {
        codigo: "M7011",
        huerto: 21,
        sector: 30,
        especie: "zarzamora",
        variedad: "tupi",
    },
    {
        codigo: "M7012",
        huerto: 02,
        sector: 13,
        especie: "frambuesa",
        variedad: "purple",
    },
    {
        codigo: "M7013",
        huerto: 01,
        sector: 02,
        especie: "arandano",
        variedad: "biloxy",
    },
    {
        codigo: "M7014",
        huerto: 02,
        sector: 03,
        especie: "zarzamora",
        variedad: "tupi",
    },
    {
        codigo: "M7015",
        huerto: 03,
        sector: 05,
        especie: "frambuesa",
        variedad: "purple",
    },
    {
        codigo: "M7016",
        huerto: 11,
        sector: 32,
        especie: "arandano",
        variedad: "biloxy",
    },
    {
        codigo: "M7017",
        huerto: 12,
        sector: 03,
        especie: "zarzamora",
        variedad: "tupi",
    },
    {
        codigo: "M7018",
        huerto: 03,
        sector: 25,
        especie: "frambuesa",
        variedad: "purple",
    },
    {
        codigo: "M7019",
        huerto: 15,
        sector: 06,
        especie: "arandano",
        variedad: "biloxy",
    },
    {
        codigo: "M7020",
        huerto: 12,
        sector: 33,
        especie: "zarzamora",
        variedad: "tupi",
    },
    {
        codigo: "M7021",
        huerto: 30,
        sector: 20,
        especie: "frambuesa",
        variedad: "purple",
    },
    {
        codigo: "M7022",
        huerto: 11,
        sector: 23,
        especie: "arandano",
        variedad: "biloxy",
    },
    {
        codigo: "M7023",
        huerto: 21,
        sector: 30,
        especie: "zarzamora",
        variedad: "tupi",
    },
    {
        codigo: "M7024",
        huerto: 02,
        sector: 13,
        especie: "frambuesa",
        variedad: "purple",
    },
]